name: Enforce Merge from Dev to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the source branch is dev
        if: ${{ github.event.pull_request.head.ref != 'dev' }}
        run: |
          echo "Error: Only merges from the 'dev' branch to 'main' are allowed."
          exit 1

  build:
    needs: check_branch
    runs-on: ubuntu-latest

    steps:
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
